### ISSUE TITLE
Issues:  Closing Kodi -> Endless Freeze & Using Live TV through PVR -> after 15-30min abrupt close

### ISSUE THREAD

**Issue by Shinoby1992** [cubicle-vdo/xbmc-israel#311]
first of all one of my top list add-on 
really thank you for always put the german channels online :-) 

like the title say if Live TV enabled i cannot close Kodi, it freezes and Hangs so i have to force close it, the other issue is that using the m3u through pvr after 15 - 30 minutes kodi just shut down

im not 100% sure but the closing issue and the abrupt shutdown issue, both problems did not exist in version 4.6.5 with resolver version 0.1.7

**Comment by avigdork** [comment]
@Shinoby1992 

Hi, there is new version 4.8.8.

I added an option in addon settings at LiveTV tab to choose a player for dynamic channels.
Try to choose Kodi-player instead of Livestreamer and restart Kodi.
This should fix the Freeze on closing Kodi. 
(I think that the combination of LiveTV and Livestreamer via local proxy causing the freeze).
