### ISSUE TITLE
Israelive 4.70 and 4.68 menu empty

### ISSUE THREAD

**Issue by SquigglyDog** [cubicle-vdo/xbmc-israel#336]
Tried installing Israelive on a Mac laptop with Kodi. Install works but when I go into Israelive the menu is empty except for Favorites. I realize the same bug was posted in November but I am not sure how to fix mine. I have tried versions 4.68 and 4.70

**Comment by avigdork** [comment]
Could you add a log file?

**Comment by SquigglyDog** [comment]
I don't have immediate access to this computer but I will post the log as soon as possible

Thanks

**Comment by avigdork** [comment]
I'll need to check why the encoding works different on MAC OS.
if you change Kodi display language to Hebrew, its working.
I don't have MAC to check it. 
send me a log file if you can.

**Comment by SquigglyDog** [comment]
I tired to get a log for you but unfortunately it is not my computer but a friends and they were not able to retrieve the log files. I don't have access any longer. Sorry

**Comment by shumi2008** [comment]
Hello avigdork,

Encountering the same issue, new installation of Kodi on mac, when opening addon, list is completely empty.
Please see error log:

22:45:48 T:140735236300800  NOTICE: special://profile/ is mapped to: special://masterprofile/
22:45:48 T:140735236300800  NOTICE: -----------------------------------------------------------------------
22:45:48 T:140735236300800  NOTICE: Starting Kodi (16.1-RC1 Git:2016-03-06-46d1480). Platform: OS X x86 64-bit
22:45:48 T:140735236300800  NOTICE: Using Release Kodi x64 build
22:45:48 T:140735236300800  NOTICE: Kodi compiled Mar  6 2016 by Clang 6.0 (clang-600.0.56) for OS X x86 64-bit version 10.7.0 (1070)
22:45:48 T:140735236300800  NOTICE: Running on Apple Inc. MacBookPro11,3 with OS X 10.11.3, kernel: Darwin x86 64-bit version 15.3.0
22:45:48 T:140735236300800  NOTICE: Host CPU: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz, 8 cores available
22:45:48 T:140735236300800  NOTICE: special://xbmc/ is mapped to: /Users/xxx/Applications/Kodi.app/Contents/Resources/Kodi
22:45:48 T:140735236300800  NOTICE: special://xbmcbin/ is mapped to: /Users/xxx/Applications/Kodi.app/Contents/Resources/Kodi
22:45:48 T:140735236300800  NOTICE: special://masterprofile/ is mapped to: /Users/xxx/Library/Application Support/Kodi/userdata
22:45:48 T:140735236300800  NOTICE: special://home/ is mapped to: /Users/xxx/Library/Application Support/Kodi
22:45:48 T:140735236300800  NOTICE: special://temp/ is mapped to: /Users/xxx/.kodi/temp
22:45:48 T:140735236300800  NOTICE: special://frameworks/ is mapped to: /Users/xxx/Applications/Kodi.app/Contents/Libraries
22:45:48 T:140735236300800  NOTICE: The executable running is: /Users/xxx/Applications/Kodi.app/Contents/MacOS/Kodi
22:45:48 T:140735236300800  NOTICE: Local hostname: xxx-lt-dev.local
22:45:48 T:140735236300800  NOTICE: Log File is located: /Users/xxx/Library/Logs/kodi.log
22:45:48 T:140735236300800  NOTICE: -----------------------------------------------------------------------
22:45:48 T:140735236300800  NOTICE: load settings...
22:45:48 T:140735236300800 WARNING: CSettingString: unknown options filler "timezonecountries" of "locale.timezonecountry"
22:45:48 T:140735236300800 WARNING: CSettingString: unknown options filler "timezones" of "locale.timezone"
22:45:48 T:140735236300800  NOTICE: Found 1 Lists of Devices
22:45:48 T:140735236300800  NOTICE: Enumerated DARWINOSX devices:
22:45:48 T:140735236300800  NOTICE:     Device 1
22:45:48 T:140735236300800  NOTICE:         m_deviceName      : default
22:45:48 T:140735236300800  NOTICE:         m_displayName     : Default
22:45:48 T:140735236300800  NOTICE:         m_displayNameExtra: MDR-XB950BT
22:45:48 T:140735236300800  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
22:45:48 T:140735236300800  NOTICE:         m_channels        : FL,FR
22:45:48 T:140735236300800  NOTICE:         m_sampleRates     : 8000,44100
22:45:48 T:140735236300800  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_FLOAT
22:45:48 T:140735236300800  NOTICE:     Device 2
22:45:48 T:140735236300800  NOTICE:         m_deviceName      : Built-in Output:stream0
22:45:48 T:140735236300800  NOTICE:         m_displayName     : Built-in Output
22:45:48 T:140735236300800  NOTICE:         m_displayNameExtra: Internal Speakers
22:45:48 T:140735236300800  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
22:45:48 T:140735236300800  NOTICE:         m_channels        : FL,FR
22:45:48 T:140735236300800  NOTICE:         m_sampleRates     : 96000,88200,48000,44100
22:45:48 T:140735236300800  NOTICE:         m_dataFormats     : AE_FMT_S24LE3,AE_FMT_S16LE,AE_FMT_FLOAT
22:45:48 T:140735236300800  NOTICE:     Device 3
22:45:48 T:140735236300800  NOTICE:         m_deviceName      : MDR-XB950BT:stream0
22:45:48 T:140735236300800  NOTICE:         m_displayName     : MDR-XB950BT
22:45:48 T:140735236300800  NOTICE:         m_displayNameExtra:
22:45:48 T:140735236300800  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
22:45:48 T:140735236300800  NOTICE:         m_channels        : FL,FR
22:45:48 T:140735236300800  NOTICE:         m_sampleRates     : 8000,44100
22:45:48 T:140735236300800  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_FLOAT
22:45:48 T:140735236300800  NOTICE:     Device 4
22:45:48 T:140735236300800  NOTICE:         m_deviceName      : Instant On Sound Effects:stream0
22:45:48 T:140735236300800  NOTICE:         m_displayName     : Instant On Sound Effects
22:45:48 T:140735236300800  NOTICE:         m_displayNameExtra:
22:45:48 T:140735236300800  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
22:45:48 T:140735236300800  NOTICE:         m_channels        : FL,FR
22:45:48 T:140735236300800  NOTICE:         m_sampleRates     : 44100
22:45:48 T:140735236300800  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
22:45:48 T:140735236300800   ERROR: CSettings: unable to load settings from special://masterprofile/guisettings.xml, creating new default settings
22:45:48 T:140735236300800  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
22:45:48 T:140735236300800  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
22:45:48 T:140735236300800  NOTICE: Default DVD Player: dvdplayer
22:45:48 T:140735236300800  NOTICE: Default Video Player: dvdplayer
22:45:48 T:140735236300800  NOTICE: Default Audio Player: paplayer
22:45:48 T:140735236300800  NOTICE: Disabled debug logging due to GUI setting. Level 0.
22:45:48 T:140735236300800  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
22:45:48 T:140735236300800  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
22:45:48 T:140735236300800  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
22:45:48 T:140735236300800  NOTICE: Loaded playercorefactory configuration
22:45:48 T:140735236300800  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
22:45:48 T:140735236300800  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
22:45:48 T:123145309356032  NOTICE: virtual bool CAESinkDARWINOSX::Initialize(AEAudioFormat &, std::string &): Opening default device MDR-XB950BT
22:45:48 T:140735236300800  NOTICE: ADDONS: Using repository repository.xbmc.org
22:45:48 T:140735236300800  NOTICE: Setup SDL
22:45:48 T:140735236300800  NOTICE: Display 0 has name Color LCD
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 1440 x 900 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 720 x 450 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 1920 x 1200 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 1680 x 1050 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 1280 x 800 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 1024 x 640 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 840 x 525 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 2880 x 1800 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 1440 x 900 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 2560 x 1600 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 2048 x 1280 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 1024 x 768 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 800 x 600 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 640 x 480 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 1680 x 1050 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Found possible resolution for display 0 with 1280 x 800 @ 60.000000 Hz
22:45:48 T:140735236300800  NOTICE: Checking resolution 16
22:45:48 T:140735236300800  NOTICE: GL_VENDOR = NVIDIA Corporation
22:45:48 T:140735236300800  NOTICE: GL_RENDERER = NVIDIA GeForce GT 750M OpenGL Engine
22:45:48 T:140735236300800  NOTICE: GL_VERSION = 2.1 NVIDIA-10.8.14 310.42.15f01
22:45:48 T:140735236300800  NOTICE: GL_SHADING_LANGUAGE_VERSION = 1.20
22:45:48 T:140735236300800  NOTICE: GL_EXTENSIONS = GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_light_max_exponent GL_NV_multisample_filter_hint GL_NV_point_sprite GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod
22:45:49 T:140735236300800  NOTICE: Running database version Addons20
22:45:49 T:140735236300800  NOTICE: start dvd mediatype detection
22:45:49 T:140735236300800 WARNING: CSkinInfo: failed to load skin settings
22:45:49 T:140735236300800 WARNING: Previous line repeats 1 times.
22:45:49 T:140735236300800 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
22:45:49 T:140735236300800  NOTICE: ActiveAE DSP - starting
22:45:49 T:140735236300800  NOTICE: initialize done
22:45:49 T:140735236300800  NOTICE: Running the application...
22:45:49 T:140735236300800  NOTICE: starting zeroconf publishing
22:45:49 T:140735236300800  NOTICE: starting upnp client
22:45:49 T:123145316409344  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
22:45:49 T:123145316409344  NOTICE: UDP: Listening on port 9777
22:46:00 T:123145309892608 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:46:11 T:123145312653312 WARNING: Previous line repeats 17 times.
22:46:11 T:123145312653312   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
22:46:11 T:123145309892608 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:46:16 T:123145312653312 WARNING: Previous line repeats 8 times.
22:46:16 T:123145312653312   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
22:46:17 T:123145309892608 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:46:21 T:123145312653312 WARNING: Previous line repeats 15 times.
22:46:21 T:123145312653312   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
22:46:21 T:123145309892608 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:46:38 T:123145312653312 WARNING: Previous line repeats 10 times.
22:46:38 T:123145312653312   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
22:46:38 T:123145309892608 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:46:44 T:123145312653312 WARNING: Previous line repeats 3 times.
22:46:44 T:123145312653312   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
22:46:46 T:123145309892608 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:46:47 T:123145303453696 WARNING: [Errno 2] No such file or directory: u'/Users/xxx/Library/Application Support/Kodi/userdata/addon_data/plugin.video.israelive/remoteSettings.txt'
22:46:47 T:123145303453696 WARNING: [Errno 2] No such file or directory: '/Users/xxx/Library/Application Support/Kodi/userdata/addon_data/plugin.video.israelive/remoteSettings.txt'
22:46:49 T:123145303453696   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'utf8' codec can't decode byte 0xd1 in position 8: unexpected end of data
                                            Traceback (most recent call last):
                                              File "/Users/xxx/Library/Application Support/Kodi/addons/plugin.video.israelive/default.py", line 37, in <module>
                                                common.UpdatePlx(plxFile, "plx", remoteSettings, forceUpdate=True)
                                              File "/Users/xxx/Library/Application Support/Kodi/addons/plugin.video.israelive/resources/lib/common.py", line 226, in UpdatePlx
                                                list1 = [{"url": item["url"], "image": item["image"], "name": item["name"].decode("utf-8"), "type": item["type"], "group": item["group"].decode("utf-8"), "id": item["id"]} for item in group]
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/encodings/utf_8.py", line 16, in decode
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 8: unexpected end of data
                                            -->End of Python script error report<--
22:46:52 T:123145312653312   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
22:46:54 T:123145309892608 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:46:56 T:123145312653312   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
22:47:54 T:123145309892608   ERROR: Previous line repeats 8 times.
22:47:54 T:123145309892608 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:48:00 T:123145312653312   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
22:49:50 T:123145309356032   ERROR: Previous line repeats 13 times.
22:49:50 T:123145309356032  NOTICE: virtual bool CAESinkDARWINOSX::Initialize(AEAudioFormat &, std::string &): Opening default device MDR-XB950BT
22:49:50 T:123145306136576 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:49:55 T:123145312116736 WARNING: Previous line repeats 3 times.
22:49:55 T:123145312116736   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
22:49:55 T:123145306136576 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:50:03 T:140735236300800 WARNING: Previous line repeats 12 times.
22:50:03 T:140735236300800 WARNING: CSkinInfo: failed to load skin settings
22:50:03 T:123145312116736   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
22:50:04 T:123145306136576 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:50:40 T:123145305063424 WARNING: Previous line repeats 76 times.
22:50:40 T:123145305063424 WARNING: [Errno 2] No such file or directory: u'/Users/xxx/Library/Application Support/Kodi/userdata/addon_data/plugin.video.israelive/lists/9999.list'
22:50:41 T:123145306136576 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:50:45 T:123145305600000 WARNING: Previous line repeats 3 times.
22:50:45 T:123145305600000 WARNING: [Errno 2] No such file or directory: u'/Users/xxx/Library/Application Support/Kodi/userdata/addon_data/plugin.video.israelive/lists/9999.list'
22:50:45 T:123145306136576 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
22:52:10 T:123145303453696 WARNING: Previous line repeats 144 times.
22:52:10 T:123145303453696 WARNING: [Errno 2] No such file or directory: u'/Users/xxx/Library/Application Support/Kodi/userdata/addon_data/plugin.video.israelive/lists/9999.list'
22:52:10 T:123145306136576 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)

**Comment by avigdork** [comment]
@shumi2008 
Hi, could you try [this version](https://github.com/cubicle-vdo/xbmc-israel/files/170858/plugin.video.israelive-4.7.7.1.zip)?
Please attach the log file. (uplad it to http://xbmclogs.com/ or http://pastebin.com/)

**Comment by shumi2008** [comment]
@avigdork 

plugin installation for both versions failed

please see error log - [http://xbmclogs.com/px4daw5ad#](url)

**Comment by avigdork** [comment]
@shumi2008 
Do you uninstall the repositoty?
You need to install the repo first:
https://github.com/cubicle-vdo/xbmc-israel/raw/master/repo/repository.xbmc-israel/repository.xbmc-israel-1.0.4.zip

**Comment by shumi2008** [comment]
@avigdork 
mybad, did not install the repo first.
(thumbsup) - perfect! works, tried 4.7.7.2

**Comment by avigdork** [comment]
:+1:
